use crate::display::{DisplayError, Segment};

pub fn glyph(c: char) -> Result<&'static [Segment], DisplayError> {
    Ok(match c {
        'A' => &[
            Segment::TopHorizontal,
            Segment::TopLeftVertical,
            Segment::TopRightVertical,
            Segment::MiddleLeft,
            Segment::MiddleRight,
            Segment::BottomLeftVertical,
            Segment::BottomRightVertical,
        ],
        'B' => &[
            Segment::TopHorizontal,
            Segment::TopRightVertical,
            Segment::TopMiddleVertical,
            Segment::MiddleLeft,
            Segment::MiddleRight,
            Segment::BottomRightVertical,
            Segment::BottomMiddleVertical,
            Segment::BottomHorizontal,
        ],
        'C' => &[
            Segment::TopHorizontal,
            Segment::TopLeftVertical,
            Segment::BottomLeftVertical,
            Segment::BottomHorizontal,
        ],
        'D' => &[
            Segment::TopHorizontal,
            Segment::TopRightVertical,
            Segment::TopMiddleVertical,
            Segment::BottomRightVertical,
            Segment::BottomMiddleVertical,
            Segment::BottomHorizontal,
        ],
        'E' => &[
            Segment::TopHorizontal,
            Segment::TopLeftVertical,
            Segment::MiddleLeft,
            Segment::BottomLeftVertical,
            Segment::BottomHorizontal,
        ],
        'F' => &[
            Segment::TopHorizontal,
            Segment::TopLeftVertical,
            Segment::MiddleLeft,
            Segment::BottomLeftVertical,
        ],
        'G' => &[
            Segment::TopHorizontal,
            Segment::TopLeftVertical,
            Segment::MiddleRight,
            Segment::BottomLeftVertical,
            Segment::BottomRightVertical,
            Segment::BottomHorizontal,
        ],
        'H' => &[
            Segment::TopLeftVertical,
            Segment::TopRightVertical,
            Segment::MiddleLeft,
            Segment::MiddleRight,
            Segment::BottomLeftVertical,
            Segment::BottomRightVertical,
        ],
        'I' => &[
            Segment::TopHorizontal,
            Segment::TopMiddleVertical,
            Segment::BottomMiddleVertical,
            Segment::BottomHorizontal,
        ],
        'J' => &[
            Segment::TopRightVertical,
            Segment::BottomLeftVertical,
            Segment::BottomRightVertical,
            Segment::BottomHorizontal,
        ],
        'K' => &[
            Segment::TopLeftVertical,
            Segment::TopRightDiagonal,
            Segment::MiddleLeft,
            Segment::BottomLeftVertical,
            Segment::BottomRightDiagonal,
        ],
        'L' => &[
            Segment::TopLeftVertical,
            Segment::BottomLeftVertical,
            Segment::BottomHorizontal,
        ],
        'M' => &[
            Segment::TopLeftVertical,
            Segment::TopLeftDiagonal,
            Segment::TopRightDiagonal,
            Segment::TopRightVertical,
            Segment::BottomLeftVertical,
            Segment::BottomRightVertical,
        ],
        'N' => &[
            Segment::TopLeftVertical,
            Segment::TopLeftDiagonal,
            Segment::TopRightVertical,
            Segment::BottomLeftVertical,
            Segment::BottomRightVertical,
            Segment::BottomRightDiagonal,
        ],
        'O' => &[
            Segment::TopHorizontal,
            Segment::TopLeftVertical,
            Segment::TopRightVertical,
            Segment::BottomLeftVertical,
            Segment::BottomRightVertical,
            Segment::BottomHorizontal,
        ],
        'P' => &[
            Segment::TopHorizontal,
            Segment::TopLeftVertical,
            Segment::TopRightVertical,
            Segment::MiddleLeft,
            Segment::MiddleRight,
            Segment::BottomLeftVertical,
        ],
        'Q' => &[
            Segment::TopHorizontal,
            Segment::TopLeftVertical,
            Segment::TopRightVertical,
            Segment::BottomLeftVertical,
            Segment::BottomRightVertical,
            Segment::BottomHorizontal,
            Segment::BottomRightDiagonal,
        ],
        'R' => &[
            Segment::TopHorizontal,
            Segment::TopLeftVertical,
            Segment::TopRightVertical,
            Segment::MiddleLeft,
            Segment::MiddleRight,
            Segment::BottomLeftVertical,
            Segment::BottomRightDiagonal,
        ],
        'S' => &[
            Segment::TopHorizontal,
            Segment::TopLeftVertical,
            Segment::MiddleLeft,
            Segment::MiddleRight,
            Segment::BottomRightVertical,
            Segment::BottomHorizontal,
        ],
        'T' => &[
            Segment::TopHorizontal,
            Segment::TopMiddleVertical,
            Segment::BottomMiddleVertical,
        ],
        'U' => &[
            Segment::TopLeftVertical,
            Segment::TopRightVertical,
            Segment::BottomLeftVertical,
            Segment::BottomRightVertical,
            Segment::BottomHorizontal,
        ],
        'V' => &[
            Segment::TopLeftVertical,
            Segment::BottomLeftVertical,
            Segment::BottomLeftDiagonal,
            Segment::TopRightDiagonal,
        ],
        'W' => &[
            Segment::TopLeftVertical,
            Segment::TopRightVertical,
            Segment::BottomLeftVertical,
            Segment::BottomLeftDiagonal,
            Segment::BottomRightDiagonal,
            Segment::BottomRightVertical,
        ],
        'X' => &[
            Segment::TopLeftDiagonal,
            Segment::TopRightDiagonal,
            Segment::BottomLeftDiagonal,
            Segment::BottomRightDiagonal,
        ],
        'Y' => &[
            Segment::TopLeftDiagonal,
            Segment::TopRightDiagonal,
            Segment::BottomMiddleVertical,
        ],
        'Z' => &[
            Segment::TopHorizontal,
            Segment::TopRightDiagonal,
            Segment::BottomLeftDiagonal,
            Segment::BottomHorizontal,
        ],
        '0' => &[
            Segment::TopHorizontal,
            Segment::TopLeftVertical,
            Segment::TopRightVertical,
            Segment::TopRightDiagonal,
            Segment::BottomLeftVertical,
            Segment::BottomRightVertical,
            Segment::BottomLeftDiagonal,
            Segment::BottomHorizontal,
        ],
        '1' => &[
            Segment::TopRightDiagonal,
            Segment::TopRightVertical,
            Segment::BottomRightVertical,
        ],
        '2' => &[
            Segment::TopHorizontal,
            Segment::TopRightVertical,
            Segment::MiddleLeft,
            Segment::MiddleRight,
            Segment::BottomLeftVertical,
            Segment::BottomHorizontal,
        ],
        '3' => &[
            Segment::TopHorizontal,
            Segment::TopRightVertical,
            Segment::MiddleLeft,
            Segment::MiddleRight,
            Segment::BottomRightVertical,
            Segment::BottomHorizontal,
        ],
        '4' => &[
            Segment::TopLeftVertical,
            Segment::TopRightVertical,
            Segment::MiddleLeft,
            Segment::MiddleRight,
            Segment::BottomRightVertical,
        ],
        '5' => &[
            Segment::TopHorizontal,
            Segment::TopLeftVertical,
            Segment::MiddleLeft,
            Segment::MiddleRight,
            Segment::BottomRightVertical,
            Segment::BottomHorizontal,
        ],
        '6' => &[
            Segment::TopHorizontal,
            Segment::TopLeftVertical,
            Segment::MiddleLeft,
            Segment::MiddleRight,
            Segment::BottomLeftVertical,
            Segment::BottomRightVertical,
            Segment::BottomHorizontal,
        ],
        '7' => &[
            Segment::TopHorizontal,
            Segment::TopRightVertical,
            Segment::BottomRightVertical,
        ],
        '8' => &[
            Segment::TopHorizontal,
            Segment::TopLeftVertical,
            Segment::TopRightVertical,
            Segment::MiddleLeft,
            Segment::MiddleRight,
            Segment::BottomLeftVertical,
            Segment::BottomRightVertical,
            Segment::BottomHorizontal,
        ],
        '9' => &[
            Segment::TopHorizontal,
            Segment::TopLeftVertical,
            Segment::TopRightVertical,
            Segment::MiddleLeft,
            Segment::MiddleRight,
            Segment::BottomRightVertical,
            Segment::BottomHorizontal,
        ],
        '-' => &[Segment::MiddleLeft, Segment::MiddleRight],
        ' ' => &[],
        _ => return Err(DisplayError::UnknownGlyph(c)),
    })
}
